### PR TITLE
Add output data format version to header

### PR DESCRIPTION
**Pull request by AyanSinhaMahapatra**
Adds a new attribute `output_format_version` to the scancode header
to support output data format versioning.
See https://github.com/nexB/scancode-toolkit/issues/2653 for more details.

Signed-off-by: Ayan Sinha Mahapatra <ayansmahapatra@gmail.com>

### CODE REVIEW

**Review by pombredanne — APPROVED** [review]
LGTM!

**Comment by pombredanne** [comment]
but in hindsight, is `output_data_format` the best name for this? Output is about a process...
What about `data_format_version` instead?

**Review by pombredanne — CHANGES_REQUESTED** [review]
IMHO `data_format_version` or `format_version` may be better names

**Comment by pombredanne** [comment]
> IMHO `data_format_version` or `format_version` may be better names

Actually your name is better. Let's keep this!

**Comment by AyanSinhaMahapatra** [comment]
Btw, just for info, this was renamed from `data_format_version` (as discussed [here](https://github.com/nexB/scancode-toolkit/issues/2653#issuecomment-902716608)) to `output_format_version` as IMHO data in scancode usually refers to the licenses/rules data, and so this could create confusion as this is more format versioning of the output, rahter than the `data`. Hence the change.

**Pull request merged**
