### PR TITLE
Use shutil.get_terminal_size()

### PR DESCRIPTION
**Pull request by georgthegreat**
click==8.1.0 [removed](https://click.palletsprojects.com/en/8.1.x/changes/#version-8-1-0) click.get_terminal_size()

### CODE REVIEW

**Comment by pombredanne** [comment]
Thank you ++! that a small change, but we still use the DCO as a base... do you mind to signoff your commit? You can also just paste that in a message in this PR to the same effect.

BTW, this makes me think we should have a CI test run that uses the latest and greatest of all dependencies. Click has been a bit problematic as 8.10 may be would have been better as 9.0 ... not that this would make a big difference.

**Comment by georgthegreat** [comment]
Signed-off-by: Yuriy Chernyshov <thegeorg@yandex-team.ru>

**Comment by georgthegreat** [comment]
> You can also just paste that in a message in this PR to the same effect.

I made this PR using GitHub WebUI, so I do not have git commit to sign.
I have copy-pasted the catchphrase. If I understood you correctly, this should be enough for DCO

**Comment by georgthegreat** [comment]
I have signed this off via git.

**Comment by AyanSinhaMahapatra** [comment]
Thanks @georgthegreat !

**Comment by pombredanne** [comment]
@georgthegreat Thank you.

**Pull request merged**
